FROM ubuntu:20.04

MAINTAINER tcneko <tcneko@outlook.com>

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates less bc iputils-ping iproute2 mtr \
  && apt-get install -y --no-install-recommends python3 python3-pip \
  && apt-get clean
RUN python3 -m pip --no-cache-dir install exabgp ipaddress
RUN mkdir -p /opt/route_creator
WORKDIR /opt/route_creator

ENTRYPOINT [ "exabgp" ]
